version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 3303:3303
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html

  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=2190705
      - MYSQL_DATABASE=nachely
    volumes:
      - ./mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: